name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET project
        run: dotnet publish -c Release -o bin/Release/net8.0/publish

      - name: Publish Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: blazor-wasm-app
          path: bin/Release/net8.0/publish

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: blazor-wasm-app

      - name: Deploy to Firebase Hosting
        uses: firebase/action-hosting-deploy@v0
        with:
          args: deploy --only hosting
          token: ${{ secrets.FIREBASE_TOKEN }}
          project: tracker-c119a
          public: blazor-wasm-app

      - name: Verify Deployment
        run: |
          echo "Deployment successful!"
          echo "Visit your preview URL: ${{ steps.deploy-to-firebase-hosting.outputs.siteUrl }}"
